---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint
spec:
  workspaces:
    - name: source
  steps:
    - name: lint
      image: python:3.8-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eux
        pip install --upgrade pip
        pip install -r requirements.txt
        make lint

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unit-tests
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: python:3.8-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eux
        pip install --upgrade pip
        pip install -r requirements.txt
        pytest -q

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image
spec:
  params:
    - name: IMAGE
      type: string
      description: Fully qualified image name (e.g. image-registry.openshift-image-registry.svc:5000/<ns>/ci-cd-final-project:latest)
  workspaces:
    - name: source
  steps:
    - name: build
      image: quay.io/buildah/stable:v1.31
      securityContext:
        privileged: true
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eux
        buildah bud -t $(params.IMAGE) .
        buildah push $(params.IMAGE)
