---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: cleanup
      image: alpine:3.19
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -eux
        rm -rf .pytest_cache || true
        rm -rf __pycache__ || true
        find . -name "*.pyc" -delete || true

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint
spec:
  workspaces:
    - name: source
  steps:
    - name: lint
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eux
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unit-tests
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eux
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        nosetests -v

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image
spec:
  params:
    - name: IMAGE
      type: string
      description: Fully qualified image name (example: image-registry.openshift-image-registry.svc:5000/<namespace>/ci-cd-final-project:latest)
  workspaces:
    - name: source
  steps:
    - name: build
      image: quay.io/buildah/stable:v1.31
      securityContext:
        privileged: true
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eux
        buildah bud -t $(params.IMAGE) .
        buildah push $(params.IMAGE)
